DROP database BRISKIT_DELIVERY_DB;
CREATE database BRISKIT_DELIVERY_DB;
USE BRISKIT_DELIVERY_DB;



-- Table: DRIVERS
CREATE TABLE DRIVERS (
  DRIVERS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USERS_ID BIGINT,
  LOCATION VARCHAR(255),
  STATUS VARCHAR(255),
  ORDERED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DELETED VARCHAR(255)
);

-- Table: LOCATION
CREATE TABLE LOCATION (
  LOCATION_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  ADDRESS_1 VARCHAR(255),
  ADDRES_2 VARCHAR(255),
  LANDMARK VARCHAR(255),
  STATE VARCHAR(255),
  COUNTRY VARCHAR(255),
  ZIP_CODE BIGINT,
  LONGITUDE DOUBLE,
  LATTITUDE DOUBLE,
  CREATED_BY BIGINT,
  DELETED VARCHAR(255)
);

-- Table: MENU_ITEMS
CREATE TABLE MENU_ITEMS (
  MENU_ITEMS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  CATEGORY VARCHAR(255),
  SERVE_START_TIME TIME,
  SERVE_END_TIME TIME,
  DESCRIPTION VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DELETED VARCHAR(255),
  PRICE DOUBLE,
  RESTAURANT_ID BIGINT
);

-- Table: ORDERS
CREATE TABLE ORDERS (
  ORDERS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  STATUS VARCHAR(255),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  USERS_ID BIGINT,
  RESTAURANT_ID BIGINT,
  TOTAL_AMOUNT DOUBLE
);
	

-- Table: RESTAURANTS
CREATE TABLE RESTAURANTS (
  RESTAURANT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  LOCATION BIGINT,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DELETED VARCHAR(255)
);

-- Table: ROLE
CREATE TABLE ROLE (
  ROLE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  CODE VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  DELTED VARCHAR(255)
);

-- Table: USERS
CREATE TABLE USERS (
  USERS_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  MIDDLE_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  ROLE_ID BIGINT,
  EMAIL VARCHAR(255) UNIQUE,
  USERNAME VARCHAR(255) UNIQUE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  DELETED VARCHAR(255)
);


-- Add forign Key constraints

ALTER Table DRIVERS
	ADD FOREIGN KEY (USERS_ID) references USERS ( USERS_ID );

ALTER Table MENU_ITEMS
	ADD FOREIGN KEY (RESTAURANT_ID) references RESTAURANTS ( RESTAURANT_ID );
	
ALTER Table ORDERS
	ADD FOREIGN KEY (USERS_ID) references USERS ( USERS_ID ),
	ADD FOREIGN KEY (RESTAURANT_ID) references RESTAURANTS ( RESTAURANT_ID );

ALTER Table USERS
	ADD FOREIGN KEY (ROLE_ID) references ROLE ( ROLE_ID );


	


